services:
  - type: web
    name: projeto-asdu
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
